name: NetflixFrontend stack build-deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push docker images
        run: |
          # Login to DockerHub         
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

          # Build and push Docker image
          NETFLIX_MOVIE_CATALOG_IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/netflixmoviecatalog:0.0.${{ github.run_number }}
          docker build -t $NETFLIX_MOVIE_CATALOG_IMAGE_NAME .
          docker push $NETFLIX_MOVIE_CATALOG_IMAGE_NAME

      - name: Checkout infrastructure repo
        uses: actions/checkout@v3
        with:
          repository: yaelwil/NetflixInfra
          token: ${{ secrets.REPO_TOKEN }}
          path: NetflixInfra

      - name: Update YAML manifests
        run: |
          NETFLIX_MOVIE_CATALOG_IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/netflixmoviecatalog:0.0.${{ github.run_number }}
          cd NetflixInfra/k8s/NetflixMovieCatalog
          sed -i "s|image: .*|image: ${NETFLIX_MOVIE_CATALOG_IMAGE_NAME}|" catalog.yaml

      - name: Configure Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Commit and Push changes
        run: |
          cd NetflixInfra
          git add *
          git commit -m "Changes to the repo ${{ github.run_number }}"
          git push origin main